[workspace]
members = [
  "utils",
  "solutions",
  "bencher",
]

default-members = ["solutions"]

[workspace.dependencies]
utils = { path = "utils" }
solutions = { path = "solutions" }

[profile.release]
debug = true

[profile.dev]
opt-level = 2
