[package]
name = "solutions"
version = "0.1.0"
edition = "2021"

[dependencies]
utils = { workspace = true }

[build-dependencies]
chrono = "0.4.23"
ureq = "*"

[[bin]]
name = "template"
path = "src/template.rs"

[[bin]]
name = "2022_01"
path = "src/2022_01.rs"

[[bin]]
name = "2022_03"
path = "src/2022_03.rs"

[[bin]]
name = "2022_04"
path = "src/2022_04.rs"

[[bin]]
name = "2022_05"
path = "src/2022_05.rs"
