[package]
name = "bencher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solutions = { workspace = true, default-features=false, features = ["all"] }
utils = { workspace = true }
